// Carbon-style framing for the documentation screenshots.
//
// Post-processes the raw PNGs produced by `npm run shots`: wraps each one in a
// rounded "window" (a title bar with three traffic-light dots), drops a soft
// shadow, and places it on a gradient backdrop. Idempotency is NOT guaranteed —
// always run on freshly captured shots: `npm run shots && npm run frame`.
//
// Run inside Docker (never on the host): ./dnode-e2e.sh npm run shots:pretty
import sharp from "sharp";
import * as path from "path";
import { existsSync, unlinkSync } from "fs";

const IMG = path.resolve("docs/img");

// The before/after set generated by tools/screenshots/capture.ts.
const NAMES = [
    "Explorer Off.png", "Explorer On.png",
    "ExplorerSort Off.png", "ExplorerSort On.png",
    "Search Off.png", "Search On.png",
    "Suggest Off 1.png", "Suggest On 1.png",
    "BookmarksOff.png", "BookmarksOn.png",
    "Backlink Off.png", "Backlink On.png",
    "Tab Off.png", "Tab On.png",
    "Heading Off.png", "Heading On.png",
    "Inline Off.png", "Inline On.png",
    "Graph Off.png", "Graph On.png",
    "Canvas Off.png", "Canvas On.png",
];

const PAD = 14; // gutter between the window and the backdrop edge
const BAR = 30; // title-bar height
const RADIUS = 10; // window corner radius
const GRAD_FROM = "#8b5cf6";
const GRAD_TO = "#6366f1";

const titleBar = (w) => Buffer.from(
    `<svg width="${w}" height="${BAR}" xmlns="http://www.w3.org/2000/svg">
        <rect width="${w}" height="${BAR}" fill="#f4f4f6"/>
        <circle cx="18" cy="${BAR / 2}" r="6" fill="#ff5f56"/>
        <circle cx="38" cy="${BAR / 2}" r="6" fill="#ffbd2e"/>
        <circle cx="58" cy="${BAR / 2}" r="6" fill="#27c93f"/>
     </svg>`
);

const roundedRect = (w, h, fill) => Buffer.from(
    `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
        <rect width="${w}" height="${h}" rx="${RADIUS}" ry="${RADIUS}" fill="${fill}"/>
     </svg>`
);

const gradient = (w, h) => Buffer.from(
    `<svg width="${w}" height="${h}" xmlns="http://www.w3.org/2000/svg">
        <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0" stop-color="${GRAD_FROM}"/>
            <stop offset="1" stop-color="${GRAD_TO}"/>
        </linearGradient></defs>
        <rect width="${w}" height="${h}" fill="url(#g)"/>
     </svg>`
);

// Side-by-side before/after hero for the README, built from the RAW Explorer
// captures (must run before the framing loop overwrites them in place).
async function buildHero() {
    const offFile = path.join(IMG, "Explorer Off.png");
    const onFile = path.join(IMG, ".hero-on.png"); // clean, un-dimmed ON capture
    if (!existsSync(offFile) || !existsSync(onFile)) {
        console.warn("[frame] hero skipped: Explorer captures not found");
        return;
    }
    const off = await sharp(offFile).png().toBuffer();
    const on = await sharp(onFile).png().toBuffer();
    const mo = await sharp(off).metadata();
    const mn = await sharp(on).metadata();

    const GAP = 28;
    const IPX = 20; // inner padding x
    const IPY = 16; // inner padding y
    const LABEL_H = 26;
    const colH = Math.max(mo.height, mn.height);
    const contentW = mo.width + GAP + mn.width;
    const cardW = IPX * 2 + contentW;
    const cardH = BAR + IPY + LABEL_H + colH + IPY;

    const labels = Buffer.from(
        `<svg width="${contentW}" height="${LABEL_H}" xmlns="http://www.w3.org/2000/svg">
            <text x="2" y="18" font-family="-apple-system,Segoe UI,Roboto,sans-serif" font-size="13" font-weight="700" fill="#9aa0aa" letter-spacing="0.6">FILENAME</text>
            <text x="${mo.width + GAP + 2}" y="18" font-family="-apple-system,Segoe UI,Roboto,sans-serif" font-size="13" font-weight="700" fill="#7c5cff" letter-spacing="0.6">FRONTMATTER TITLE</text>
         </svg>`
    );

    const card = await sharp({ create: { width: cardW, height: cardH, channels: 4, background: "#ffffff" } })
        .composite([
            { input: titleBar(cardW), top: 0, left: 0 },
            { input: labels, top: BAR + IPY, left: IPX },
            { input: off, top: BAR + IPY + LABEL_H, left: IPX },
            { input: on, top: BAR + IPY + LABEL_H, left: IPX + mo.width + GAP },
            { input: roundedRect(cardW, cardH, "#ffffff"), blend: "dest-in" },
        ])
        .png()
        .toBuffer();

    const shadow = await sharp(roundedRect(cardW, cardH, "rgba(10,12,20,0.45)")).blur(22).png().toBuffer();
    const W = cardW + PAD * 2;
    const H = cardH + PAD * 2;

    await sharp(gradient(W, H))
        .composite([
            { input: shadow, top: PAD + 14, left: PAD },
            { input: card, top: PAD, left: PAD },
        ])
        .png()
        .toFile(path.join(IMG, "hero.png"));

    unlinkSync(onFile); // drop the temp clean capture
    console.log(`[frame] hero.png (${W}x${H})`);
}

async function frame(name) {
    const file = path.join(IMG, name);
    if (!existsSync(file)) {
        console.warn(`[frame] skip ${name}: not found`);
        return;
    }
    const shot = await sharp(file).png().toBuffer();
    const meta = await sharp(shot).metadata();
    const w = meta.width;
    const h = meta.height;
    const cardW = w;
    const cardH = h + BAR;

    // Window card: white base + title bar + screenshot, clipped to rounded corners.
    const card = await sharp({ create: { width: cardW, height: cardH, channels: 4, background: "#ffffff" } })
        .composite([
            { input: titleBar(cardW), top: 0, left: 0 },
            { input: shot, top: BAR, left: 0 },
            { input: roundedRect(cardW, cardH, "#ffffff"), blend: "dest-in" },
        ])
        .png()
        .toBuffer();

    // Soft drop shadow: a blurred dark rounded rect the size of the card.
    const shadow = await sharp(roundedRect(cardW, cardH, "rgba(10,12,20,0.45)"))
        .blur(22)
        .png()
        .toBuffer();

    const W = cardW + PAD * 2;
    const H = cardH + PAD * 2;

    await sharp(gradient(W, H))
        .composite([
            { input: shadow, top: PAD + 14, left: PAD },
            { input: card, top: PAD, left: PAD },
        ])
        .png()
        .toFile(file);

    console.log(`[frame] ${name} (${W}x${H})`);
}

await buildHero();
for (const name of NAMES) await frame(name);
console.log("[frame] done");
