import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import * as fs from "fs";

const manifestStr =  fs.readFileSync("manifest.json", "utf-8");
const manifest = JSON.parse(manifestStr);

// Extract the current version's section from CHANGELOG.md (without its "## x.y.z"
// heading) so the "what's new" modal shows notes specific to this version instead
// of a hardcoded message. Same source as the GitHub Release notes.
function readWhatsNew(version) {
	try {
		const lines = fs.readFileSync("CHANGELOG.md", "utf-8").split(/\r?\n/);
		const out = [];
		let capture = false;
		for (const line of lines) {
			if (line.startsWith("## ")) {
				capture = line.slice(3).trim() === version;
				continue;
			}
			if (capture) out.push(line);
		}
		return out.join("\n").trim();
	} catch {
		return "";
	}
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
const PLUGIN_VERSION="${manifest.version}";
const PLUGIN_WHATS_NEW=${JSON.stringify(readWhatsNew(manifest.version))};
`;

const prod = (process.argv[2] === "production");

// prod keeps main.js in the repo root (pack-release.mjs expects it there);
// dev/watch writes to dist/ together with a copy of manifest.json, so the
// folder holds exactly the two files Obsidian needs and can be synced to a vault.
const outfile = prod ? "main.js" : "dist/main.js";

const copyManifestPlugin = {
	name: "copy-manifest",
	setup(build) {
		build.onEnd(() => {
			fs.mkdirSync("dist", { recursive: true });
			fs.copyFileSync("manifest.json", "dist/manifest.json");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	plugins: prod ? [] : [copyManifestPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
