import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import * as fs from "fs";

const manifestStr =  fs.readFileSync("manifest.json", "utf-8");
const manifest = JSON.parse(manifestStr);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
const PLUGIN_VERSION="${manifest.version}";
`;

const prod = (process.argv[2] === "production");

// prod keeps main.js in the repo root (pack-release.mjs expects it there);
// dev/watch writes to dist/ together with a copy of manifest.json, so the
// folder holds exactly the two files Obsidian needs and can be synced to a vault.
const outfile = prod ? "main.js" : "dist/main.js";

const copyManifestPlugin = {
	name: "copy-manifest",
	setup(build) {
		build.onEnd(() => {
			fs.mkdirSync("dist", { recursive: true });
			fs.copyFileSync("manifest.json", "dist/manifest.json");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	plugins: prod ? [] : [copyManifestPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
